---
baseURL: http://escolarugbyporto.pt
languageCode: pt-PT
title: Escola Rugby do Porto
module:
  imports:
  - path: github.com/escolarugbyporto/gohugo-theme-ananke
DefaultContentLanguage: pt
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: Escola Rugby Porto.
  facebook: 'https://www.facebook.com/escolarugbyporto/'
  twitter: ''
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: "/images/porto-bridge.png"
  recent_posts_number: 2
