name: Publish Site

on:
  push:
    branches:
    - master # Branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'

    - name: Build
      run: hugo -D

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server:   ${{ secrets.PUBLISH_FTP_SERVER }}
        ftp-username: ${{ secrets.PUBLISH_FTP_USERNAME }}
        ftp-password: ${{ secrets.PUBLISH_FTP_PASSWORD }}
        local-dir: public/
        server-dir: public/www
        log-level: standard