name: Publish Site

on:
  schedule:
  	- cron: '» 23 » » »'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'

    - name: Build
      run: hugo -D

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:   ${{ secrets.PUBLISH_FTP_SERVER }}
        username: ${{ secrets.PUBLISH_FTP_USERNAME }}
        password: ${{ secrets.PUBLISH_FTP_PASSWORD }}
        local-dir: public/
        server-dir: public/www/
        log-level: standard